package io.wxwobot.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWxPyqRelate<M extends BaseWxPyqRelate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAppId(java.lang.Integer appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Integer getAppId() {
		return getInt("app_id");
	}

	public M setOutKey(java.lang.String outKey) {
		set("out_key", outKey);
		return (M)this;
	}
	
	public java.lang.String getOutKey() {
		return getStr("out_key");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public M setPyqId(java.lang.Integer pyqId) {
		set("pyq_id", pyqId);
		return (M)this;
	}
	
	public java.lang.Integer getPyqId() {
		return getInt("pyq_id");
	}

	public M setPyqShowId(java.lang.Integer pyqShowId) {
		set("pyq_show_id", pyqShowId);
		return (M)this;
	}
	
	public java.lang.Integer getPyqShowId() {
		return getInt("pyq_show_id");
	}

}
