package io.wxwobot.admin.web.model;

import io.wxwobot.admin.web.model.base.BaseWxPyqRelate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxPyqRelate extends BaseWxPyqRelate<WxPyqRelate> {
    public static final WxPyqRelate dao = new WxPyqRelate().dao();
}
