package io.wxwobot.admin.web.model;

import io.wxwobot.admin.web.model.base.BaseWxRobConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxRobConfig extends BaseWxRobConfig<WxRobConfig> {
    public static final WxRobConfig dao = new WxRobConfig().dao();

    private boolean isActive;

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }
}
