package io.wxwobot.admin.web.model;

import io.wxwobot.admin.web.model.base.BaseWxRobKeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxRobKeyword extends BaseWxRobKeyword<WxRobKeyword> {
    public static final WxRobKeyword dao = new WxRobKeyword().dao();
}
