package io.wxwobot.admin.web.model;

import io.wxwobot.admin.web.model.base.BaseWxRobRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxRobRelation extends BaseWxRobRelation<WxRobRelation> {
	
}
